import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Crimson_Text  } from "next/font/google";
import "./globals.css";
import "@/app/styles/platformStructure.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey = Montserrat({
  weight: "400",
  variable: "--font-jersey-15",
  subsets: ["latin"],
});

const crimsonText = Crimson_Text({
  weight: "400",
  variable: "--font-crimson-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kelson Victor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jersey.variable} ${crimsonText.variable} antialiased`}
      >
        {children}
        <svg style={{ position: "absolute", width: 0, height: 0, opacity: 0.1 }}>
          <filter id="grainy" x="-20%" y="-20%" width="140%" height="140%" filterUnits="objectBoundingBox" primitiveUnits="userSpaceOnUse" colorInterpolationFilters="linearRGB">
            <feTurbulence type="turbulence" baseFrequency="0.196" numOctaves="4" seed="15" stitchTiles="stitch" x="0%" y="0%" width="100%" height="100%" result="turbulence"></feTurbulence>
            <feSpecularLighting surfaceScale="11" specularConstant="0.3" specularExponent="20" lightingColor="#ffffff" x="0%" y="0%" width="100%" height="100%" in="turbulence" result="specularLighting">
              <feDistantLight azimuth="3" elevation="12"></feDistantLight>
            </feSpecularLighting>
          </filter>
        </svg>

        <svg xmlns="http://www.w3.org/2000/svg" style={{ position: "absolute", width: 0, height: 0, opacity: 0.1 }}>
          <defs>
            <filter id="goo">
              <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
              <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8" result="goo" />
              <feBlend in="SourceGraphic" in2="goo" />
            </filter>
          </defs>
        </svg>
      </body>
    </html>
  );
}
